sudo: require
services:
  - docker

before_install:
  - docker build -t youssefsamih/docker-react-tuto -f Dockerfile.dev .

script:
  - docker run -e CI=true youssefsamih/docker-react-tuto npm run test -- --coverage
